version: "3.9"

networks:
  rinha-network:
    driver: bridge


services:
  rinha-postgres:
    volumes:
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql
    image: postgres:latest
    environment:
      POSTGRES_DB: rinha
      POSTGRES_USER: rinha
      POSTGRES_PASSWORD: rinha
    ports:
      - "5432:5432"
    networks:
      - rinha-network
#    deploy:
#      resources:
#        limits:
#          memory: "300MB"
#          cpus: "0.5"


  api1:
    image: thiagotnunes08/rinha-api-2:3.2
    hostname: api1
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://rinha-postgres:5432/rinha
    ports:
      - "8080"
    networks:
      - rinha-network
    depends_on:
      - rinha-postgres
#    deploy:
#      resources:
#        limits:
#          memory: "125MB"
#          cpus: "0.25"

  api2:
    image: thiagotnunes08/rinha-api-2:3.2
    hostname: api2
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://rinha-postgres:5432/rinha
    ports:
      - "8080"
    networks:
      - rinha-network
    depends_on:
      - rinha-postgres
#    deploy:
#      resources:
#        limits:
#          memory: "125MB"
#          cpus: "0.25"

  nginx:
    image: nginx:1.17.6-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9999:9999"
    networks:
      - rinha-network
    depends_on:
      - api1
      - api2
#    deploy:
#      resources:
#        limits:
#          memory: "50MB"
#          cpus: "0.25"